config/routes.rb
Rails.application.routes.draw do
  resources :appointments

  root 'appointments#index'
  get 'gallery' => 'appointments#gallery'
  get 'about' => 'appointments#about'
  get 'calendar' => 'appointments#calendar'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController
  before_action :set_appointment, only: [:show, :edit, :update, :destroy]

  # GET /appointments
  # GET /appointments.json
  def index
    @appointments = Appointment.all
    @appointment = Appointment.new
  end

  # GET /appointments/1
  # GET /appointments/1.json
  def show
  end

  def about
  end

  def gallery
  end

  def calendar
    @appointment = Appointment.new
  end

  # GET /appointments/new
  def new
    @appointment = Appointment.new
  end

  # GET /appointments/1/edit
  def edit
  end

  # POST /appointments
  # POST /appointments.json
  def create
    @appointment = Appointment.new(appointment_params)
    UserMailer.request_email(@appointment).deliver_now
    UserMailer.confirmation_email(@appointment).deliver_now
    respond_to do |format|
      if @appointment.save
        format.html { redirect_to @appointment, notice: 'Appointment was successfully created.' }
        format.json { render :show, status: :created, location: @appointment }
      else
        format.html { render :new }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /appointments/1
  # PATCH/PUT /appointments/1.json
  def update
    respond_to do |format|
      if @appointment.update(appointment_params)
        format.html { redirect_to @appointment, notice: 'Appointment was successfully updated.' }
        format.json { render :show, status: :ok, location: @appointment }
      else
        format.html { render :edit }
        format.json { render json: @appointment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /appointments/1
  # DELETE /appointments/1.json
  def destroy
    @appointment.destroy
    respond_to do |format|
      format.html { redirect_to appointments_url, notice: 'Appointment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_appointment
      @appointment = Appointment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def appointment_params
      params.require(:appointment).permit(:name, :email, :phone_num, :address, :event_details, :date, :time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/views/appointments/_form.html.erb
<%= form_with(model: appointment, local: true) do |form| %>
  <% if appointment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(appointment.errors.count, "error") %> prohibited this appointment from being saved:</h2>

      <ul>
      <% appointment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :name %>
    <%= form.text_field :name, id: :appointment_name, required: true, class:"form-control"%>
  </div>

  <div class="form-group">
    <%= form.label :email %>
    <%= form.text_field :email, id: :appointment_email, required: true, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :phone_number%>
    <%= form.text_field :phone_num, id: :appointment_phone_num, required: true, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %>
    <%= form.text_field :address, id: :appointment_address, required: true, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :event_details %>
    <%= form.text_area :event_details, id: :appointment_event_details, required: true, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date %>
    <%= form.text_field :date, id: :appointment_date, required: true, class:"form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :time %>
    <%= form.text_field :time, id: :appointment_time, required: true, class:"form-control"%>
  </div>

  <div class="actions">
    <%= form.submit  "Submit Event Request", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/appointments/about.html.erb
<!DOCTYPE html>
<html>
<div class="aboutimg">
</div>
  <head>
    <div class="aboutimg">
    </div>
    <link href = "about.scss" rel = "stylesheet" type = "text/scss">
    <meta charset="utf-8">
    <title>About Me</title>
  </head>
  <body>
     <div class="header">
    <div class="logo">
      <%= image_tag("logo.png", :size => "130x75") %>

      <p><%= link_to 'BOOK EVENT', calendar_path, class: "navbar-brand" %></p>
      <p><%= link_to 'GALLERY', gallery_path, class: "navbar-brand" %></p>
      <p><%= link_to 'ABOUT', about_path, class: "navbar-brand" %></p>
      <p><%= link_to 'HOME', root_path, class: "navbar-brand" %></p>
    </div>
  </div>

    <div class="container">
      <div class= "abouth1">

        <h1>About Me</h1>

        <div class="col-md-6">
          <%= image_tag("image1.jpg") %>
        </div>

        <div class="col-md-5">
          <p>I grew up in the era of house parties.  Almost every weekend my mom would have house parties and invite her friends over to play games and listen to music.  Being that I was only 5 years old, I remember sneaking out of my room to watch them.  What they didn’t know was I was watching their reactions to songs.  I was truly fascinated with how a song could move a person.  Bring life to a party or bring back a memory.  It was during this age when I would sneak out of the room and change the song for them.   I would get 6, sometimes 8 songs in a row before they noticed it was me, and yell “ Go to Bed”. Two songs later I am back out changing to then next song. </p>

          <p>I remember one time someone said how does he know all our favorites songs.  They didn’t know I just remembered all parties and which song brought the greatest joy out of whoever was there.  And that’s where it began.  By the next few parties, my mom would let me play the music all night long!  This carried over to high-school where I would Dj all my friends parties.</p>

          <p>Music is a book for me.  I can sit for hours in a room and just listen to songs of every genre.  I mean truly every genre. I just love the sounds, the word play, the beat and the emotion it carries.  This has helped me be a Dj that can rock any party regardless of genres my mixes will bring you an experience that will exceed your expectations.</p>
        </div>
      </div>
  </div>
  </body>
</html>

app/views/appointments/calendar.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Calendar</title>
  </head>
  <body>
    <div class="calendar">
     <div class="header">
    <div class="logo">
      <%= image_tag("logo.png", :size => "130x75") %>

      <p><%= link_to 'BOOK EVENT', calendar_path, class: "navbar-brand" %></p>
      <p><%= link_to 'GALLERY', gallery_path, class: "navbar-brand" %></p>
      <p><%= link_to 'ABOUT', about_path, class: "navbar-brand" %></p>
      <p><%= link_to 'HOME', root_path, class: "navbar-brand" %></p>
    </div>
  </div>
    <div class="title">
    <h1>Want DJ Crues at your next event?</h1>
    <h3> Please check out my calendar for availability and send over a booking request! </h3>
  </div>

  <div class="container">
      <div class= "col-md-3">
             <%= render 'form', appointment: @appointment %>
      </div>
       <div class= "col-md-8">
          <iframe src="https://calendar.google.com/calendar/embed?height=600&amp;wkst=1&amp;bgcolor=%23ffffff&amp;src=crumusicgroup%40gmail.com&amp;color=%23125A12&amp;ctz=America%2FPhoenix" style="border-width:0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
      </div>
  </div>
</div>
  </body>
</html>

app/views/appointments/edit.html.erb
<h1>Editing Appointment</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Show', @appointment %> |
<%= link_to 'Back', appointments_path %>

app/views/appointments/gallery.html.erb
<html>
<head>
  <div class="header">
    <div class="logo">
      <%= image_tag("logo.png", :size => "130x75") %>

      <p><%= link_to 'BOOK EVENT', calendar_path, class: "navbar-brand" %></p>
      <p><%= link_to 'GALLERY', gallery_path, class: "navbar-brand" %></p>
      <p><%= link_to 'ABOUT', about_path, class: "navbar-brand" %></p>
      <p><%= link_to 'HOME', root_path, class: "navbar-brand" %></p>
    </div>
  </div>

</head>
<body>
  <div class="container">
    <div class="col-md-12" id="spinpic">
      <img src=/assets/djc.jpg alt="picture">
    </div>
    <div class="gallery">
      <img src=/assets/dje2.jpeg alt="picture">
    </div>
    <div class="gallery">
      <img src=/assets/image2.png alt="picture">
    </div>
    <div class="gallery">
      <img src=/assets/atlas2.jpg alt="picture">
    </div>
    <div class="gallery">
      <img src=/assets/djequip.jpeg alt="picture">
    </div>
    <div class="gallery">
      <img src=/assets/djc2.jpg alt="picture">
    </div>
    <div class="gallery">
      <img src=/assets/image1.jpg alt="picture">
    </div>
  </div>
</body>
</html>

app/views/appointments/index.html.erb
<body id="gif">
<div class="header">
    <div class="logo">
      <%= image_tag("logo.png", :size => "130x75") %>

      <p><%= link_to 'BOOK EVENT', calendar_path, class: "navbar-brand" %></p>
      <p><%= link_to 'GALLERY', gallery_path, class: "navbar-brand" %></p>
      <p><%= link_to 'ABOUT', about_path, class: "navbar-brand" %></p>
      <p><%= link_to 'DJ CRUES', root_path, class: "navbar-brand" %></p>
    </div>
  </div>

<!-- <h1 id="front"> Dj Crues</h1> -->
<div id="mainpage">


</div>
</body>

app/views/appointments/new.html.erb
<h1>Book DJ Crues for your next event</h1>

<%= render 'form', appointment: @appointment %>

<%= link_to 'Back', appointments_path %>

app/views/appointments/show.html.erb
<div class="header">
    <div class="logo">
      <%= image_tag("logo.png", :size => "130x75") %>

      <p><%= link_to 'BOOK EVENT', calendar_path, class: "navbar-brand" %></p>
      <p><%= link_to 'GALLERY', gallery_path, class: "navbar-brand" %></p>
      <p><%= link_to 'ABOUT', about_path, class: "navbar-brand" %></p>
      <p><%= link_to 'HOME', root_path, class: "navbar-brand" %></p>
    </div>
  </div>

<div id="showpage">
<h1>Thank you for requesting an event with DJ Crues!</h1>
<h3>We will be reaching out to confirm the following informtion:</h3>

<p>
  <strong>Name:</strong>
  <%= @appointment.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @appointment.email %>
</p>

<p>
  <strong>Phone Number:</strong>
  <%= @appointment.phone_num %>
</p>

<p>
  <strong>Address:</strong>
  <%= @appointment.address %>
</p>

<p>
  <strong>Event Details:</strong>
  <%= @appointment.event_details %>
</p>

<p>
  <strong>Date:</strong>
  <%= @appointment.date %>
</p>

<p>
  <strong>Time:</strong>
  <%= @appointment.time %>
</p>

<%= link_to 'Edit', edit_appointment_path(@appointment) %> |
<%= link_to 'Back', appointments_path %>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">

   <div class="container-fluid">
      <div class="container">
        <div class="navbar-header">
            <%= link_to 'Home', root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-header">
            <%= link_to 'About', about_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-header">
            <%= link_to 'Gallery', gallery_path, class: "navbar-brand" %>
          </div>
        <div class="navbar-header">
          <%= link_to 'Book Event', calendar_path, class: "navbar-brand" %>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CruMusicGroup</title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>


  </head>
  <header>
  <body>



<%= yield %>

</header>
  </body>
</html>

app/views/layouts/nav.js.erb
$(document).ready(function() {

  function toggleSidebar() {
    $(".button").toggleClass("active");
    $("main").toggleClass("move-to-left");
    $(".sidebar-item").toggleClass("active");
  }

  $(".button").on("click tap", function() {
    toggleSidebar();
  });

  $(document).keyup(function(e) {
    if (e.keyCode === 27) {
      toggleSidebar();
    }
  });

});